Migrated all core mod functionality from ASM Transformers to Mixins
GTNewHorizons/Battlegear2 pull request #17
Opened 2023-04-08 06:55 UTC by cottonman132

2023-04-08 08:57 UTC, glowredman requested changes
1. Please provide a description of your PR. What you did, why you did it, what other effects the PR has, etc.
2. The Battlegear API is occasionally used in other mods. You're changes are most likely breaking that compat because you're changing method names for no good reason (see other comment), as well as the transition from `InventoryPlayerBattle` to `IBattlegearInventoryPlayer`.
3. By using Mixins, you are automatically adding a dependency where there hasn't been one before.

Essentially you are trading slightly better maintainability against an additional dependency and completely breaking other mod's compat. I don't think this is worth it.

2023-04-08 08:57 UTC, glowredman commented on src/main/java/mods/battlegear2/api/core/IBattlePlayer.java
Why are you changing the method names here?

2023-04-08 20:24 UTC, Dream-Master commented
@cottonman132

2023-04-09 07:08 UTC, cottonman132 commented on src/main/java/mods/battlegear2/api/core/IBattlePlayer.java
I updated them because it makes it easier for me to understand the code when the method names are a bit more descriptive. Is this is a problem, I believe you should be able to change them back.

2023-04-09 07:12 UTC, cottonman132 commented
I updated the PR description with the best summary I could think of (which probably sucks because I'm not really great at writing descriptions and/or summaries). If there anything specific you need me to write out, you can ask me directly

2023-05-30 15:06 UTC, Dream-Master commented
@cottonman132 are you able to make it backwards compatible or should i close this. We cant merge this in the current state.

2023-05-30 15:17 UTC, cottonman132 commented
I'm sorry but I think making it backwards compatible would be more work than I'm willing to put in. If you want to close the PR it's fine by me

2023-05-30 15:21 UTC, Dream-Master commented
ok

2023-05-30 15:21 UTC, closed without merging